### ISSUE TITLE
Data should be persisted into a database rather than ad-hoc files

### ISSUE THREAD

**Issue by MaybeJustJames** [aertslab/SCope#245]
This is a large tracking task for several related sub-tasks:

- [x] Define data that may be stored in a database and/or on the filesystem [#284].
- [x] Define a draft schema for the database [#285].
- [x] Set up `SQLAlchemy` and `Alembic` [#321].
- [x] Set up schemas and objects per draft schema [#287].
